import type { ChainName, SupermarketAisle } from "@/app/types/api.types";

export const SUPERMARKET_CHAINS: readonly ChainName[] = [
  "aldi",
  "bennet",
  "centesimo",
  "crai",
  "decomarket",
  "decosupermercati",
  "despar",
  "esselunga",
  "eurospar",
  "eurospin",
  "famila",
  "familamarket",
  "familasuperstore",
  "gigante",
  "gulliver",
  "ins",
  "interspar",
  "iper",
  "lidl",
  "md",
  "mercatobig",
  "mercatoextra",
  "mercatolocal",
  "naturasi",
  "paghipoco",
  "pam",
  "pampanorama",
  "pamsuperstore",
  "penny",
  "prestofresco",
  "tigros",
  "todis",
  "unes",
] as const;

export const SUPERMARKET_AISLES: readonly SupermarketAisle[] = [
  "frutta e verdura",
  "carne",
  "pesce",
  "salumi",
  "formaggi",
  "pasta e riso",
  "vino",
  "birra",
  "snack salati",
  "snack dolci",
  "surgelati",
  "in scatola",
  "per la colazione",
  "bio",
  "senza lattosio",
  "asiatico",
  "multietnico",
  "vegano",
  "vegetariano",
  "fitness",
  "per il bambino",
  "per la casa",
  "per la persona",
  "per il tuo mezzo di trasporto",
  "animali domestici",
  "giardinaggio",
  "abbigliamento",
  "elettrodomestici",
  "bricolage",
  "super alcolici",
  "spesa base",
] as const;

export const SUPERMARKET_DISPLAY_NAMES: Record<ChainName, string> = {
  aldi: "Aldi",
  bennet: "Bennet",
  centesimo: "Centesimo",
  crai: "Crai",
  decomarket: "Deco Market",
  decosupermercati: "Deco Supermercati",
  despar: "Despar",
  esselunga: "Esselunga",
  eurospar: "Eurospar",
  eurospin: "Eurospin",
  famila: "Famila",
  familamarket: "Famila Market",
  familasuperstore: "Famila Superstore",
  gigante: "Gigante",
  gulliver: "Gulliver",
  ins: "Ins",
  interspar: "Interspar",
  iper: "Iper",
  lidl: "Lidl",
  md: "MD",
  mercatobig: "Mercato Big",
  mercatoextra: "Mercato Extra",
  mercatolocal: "Mercato Local",
  naturasi: "NaturaSì",
  paghipoco: "Paghi Poco",
  pam: "Pam",
  pampanorama: "Pam Panorama",
  pamsuperstore: "Pam Superstore",
  penny: "Penny",
  prestofresco: "Presto Fresco",
  tigros: "Tigros",
  todis: "Todis",
  unes: "Unes",
};
