import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const sfProDisplay = localFont({
  src: [
    {
      path: "../public/fonts/SFProDisplay/SFProDisplay-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/SFProDisplay/SFProDisplay-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/SFProDisplay/SFProDisplay-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sfpro",
  display: "swap",
});



export const metadata: Metadata = {
  title: "IL Prezzo Giusto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${sfProDisplay.variable} font-figtree antialiased`}
      >
        <div className="max-w-[575px] w-full mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
